# Generated by Django 3.0.7 on 2020-06-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('piggybank', models.IntegerField(default=0)),
                ('flex', models.IntegerField(default=0)),
                ('flex_dollars', models.IntegerField(default=0)),
                ('safelock', models.IntegerField(default=0)),
                ('investify', models.IntegerField(default=0)),
            ],
        ),
    ]
